import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CartProvider from "@/components/Provider";
import { Toaster } from "react-hot-toast";


const font = Josefin_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ecommerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">


      <body className={`${font.className} ${font.className} antialiased`}>
        <CartProvider>
          <div className="max-w-[1920px] mx-auto">
            <Header />
            <Navbar />
            <Toaster />
            {children}
            <Footer />
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
